INSERT INTO places (id, place, description) VALUES (1, 'москва', 'Не забудьте посетить Красную Площадь. Ну а в ЦУМ можно и не заходить)))');
INSERT INTO places (id, place, description) VALUES (2, 'минск', 'Обязательно посетите Троицкое предместье');
INSERT INTO places (id, place, description) VALUES (3, 'варшава', 'Обязательно посетите Королевский замок');
INSERT INTO places (id, place, description) VALUES (4, 'вильнюс', 'Обязательно посетите Башня замка Гядиминаса');
INSERT INTO places (id, place, description) VALUES (5, 'берлин', 'Не забудьте посетить Бранденбургские ворота');
INSERT INTO places (id, place, description) VALUES (6, 'париж', 'Обязательно посетите Эйфелеву башню');
INSERT INTO places (id, place, description) VALUES (7, 'рим', 'Советую посетить Древнейший амфитеатр Колизей');
INSERT INTO places (id, place, description) VALUES (8, 'вена', 'Советую посетить Дворец Хофбург');
INSERT INTO places (id, place, description) VALUES (9, 'амстердам', 'Советую посетить Музей Ван Гога');
INSERT INTO places (id, place, description) VALUES (10, 'барселона', 'Обязательно посетите  Храм Святого Семейства');
INSERT INTO places (id, place, description) VALUES (11, 'брюссель', 'Обязательно посетите Атомиум');
INSERT INTO places (id, place, description) VALUES (12, 'софия', 'Не забудьте посетить Храм-памятник Александра Невского');
INSERT INTO places (id, place, description) VALUES (13, 'ватикан', 'Не забудьте посетить Собор Святого Петра');
INSERT INTO places (id, place, description) VALUES (14, 'лондон', 'Обязательно посетите Букингемский дворец');
INSERT INTO places (id, place, description) VALUES (15, 'афины', 'Обязательно посетите Древнегреческий храм Парфенон');
INSERT INTO places (id, place, description) VALUES (16, 'копенгаген', 'Обязательно посетите дворец Амалиенборг');
INSERT INTO places (id, place, description) VALUES (17, 'мадрид', 'Обязательно посетите Королевский дворец ');
INSERT INTO places (id, place, description) VALUES (18, 'рига', 'Обязательно посетите Домский собор');
INSERT INTO places (id, place, description) VALUES (19, 'осло', 'Советую посетить Парк скульптур Вигеланда');
INSERT INTO places (id, place, description) VALUES (20, 'лиссабон', 'Советую посетить замкок Святого Георгия');
INSERT INTO places (id, place, description) VALUES (21, 'бухарест', 'Советую посетить Деревенский музей Muzeul National al Satului "Dimitrie Gusti"');
INSERT INTO places (id, place, description) VALUES (22, 'белград', 'Советую посетить Белградскую крепость');
INSERT INTO places (id, place, description) VALUES (23, 'киев', 'Советую посетить Киево-Печерскую лавру');
INSERT INTO places (id, place, description) VALUES (24, 'хельсинки', 'Кафедральный собор и Сенатская площадь');
INSERT INTO places (id, place, description) VALUES (25, 'прага', 'Не забудьте посетить Карлов мост');
INSERT INTO places (id, place, description) VALUES (26, 'загреб', 'Не забудьте посетить Собор Вознесения Девы Марии');
INSERT INTO places (id, place, description) VALUES (27, 'берн', 'Обязательно посетите Бернские фонтаны');
INSERT INTO places (id, place, description) VALUES (28, 'стокгольм', 'Обязательно посетите Королевский дворец');
INSERT INTO places (id, place, description) VALUES (29, 'таллинн', 'Обязательно посетите Старую Ратушу');
INSERT INTO places (id, place, description) VALUES (30, 'стамбул', 'Обязательно посетите Голубую мечеть Султанахмет');